apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: order-service
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: andy2025/order-service:c2852b8
        ports:
        - containerPort: 8082

        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://${DB_ENDPOINT}:5432/${DB_NAME}"

          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username

          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
                
          - name: USER_SERVICE_URL
            value: http://user-service:8080/user
          - name: PRODUCT_SERVICE_URL
            value: http://product-service:8081/product
          - name: SPRING_PROFILES_ACTIVE

